IDSFFile: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/SFs/UL2016postVFP_mu_HLT.json"
kinematics: 
    Muon:
        lohi:
            pt:
                low: 26
                high: 2000
            eta:
                low: -2.4
                high: 2.4
            pfRelIso04_all:
                low: 
                high: 
        value: 
            tightId: 1
        correctionLib:
            weightName: "{'UL2016preVFP': 'NUM_IsoMu24_or_IsoTkMu24_DEN_CutBasedIdTight_and_PFIsoTight', 'UL2016postVFP': 'NUM_IsoMu24_or_IsoTkMu24_DEN_CutBasedIdTight_and_PFIsoTight', 'UL2017': 'NUM_IsoMu27_DEN_CutBasedIdTight_and_PFIsoTight', 'UL2018': 'NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight'}"
        branchNames:
            sf: "MuonHLTWeight"
            sfstat: "MuonHLTWeightStat"
            sfsyst: "MuonHLTWeightSyst"
        