#!/usr/bin/env python3
"""
Master script to generate all outputs for 002-Samples chapter.

This chapter spans two environments:
  - lxplus: DAS querying, golden JSON download, luminosity info, and CRAB
    submission/monitoring for the preselection stage. Output ROOT files land
    on EOS under LFN_Base.
  - Wherever the analysis actually runs (e.g. cms2): once the CRAB output
    ROOT files have been copied/staged to local disk under
    {STORAGE}/preselection/{tag}/{era}/..., --generatePreselectionDatasetJSON
    scans them and produces preselection_{era}_datasets.json, the input
    003-ObjectSelectionI expects.

Usage:
    python scripts/run_all.py --tag TAG_NAME [--force] [--filter ...] [step flags]

Options:
    --force: Regenerate outputs even if config hash already exists
    --tag: Create a named tag for this run (e.g., "earlyApril")
"""

import argparse
import sys
from pathlib import Path
import subprocess
import json

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))
import utils


def matches_filter(filters, era, data_mc=None, group=None, dataset=None):
    """Check if era/DataMC/group/dataset matches any of the provided filters.

    Each filter is a slash-separated string, e.g. 'UL2017/MC_mu/SingleTop/Tchannel'.
    Use '*' as a wildcard for any level.
    A shorter filter path matches all entries at deeper levels.
    """
    if not filters:
        return True
    for f in filters:
        parts = f.split('/')
        if parts[0] not in ('*', era):
            continue
        if data_mc is not None and len(parts) >= 2 and parts[1] not in ('*', data_mc):
            continue
        if group is not None and len(parts) >= 3 and parts[2] not in ('*', group):
            continue
        if dataset is not None and len(parts) >= 4 and parts[3] not in ('*', dataset):
            continue
        return True
    return False


def main():
    parser = argparse.ArgumentParser(description='Generate all outputs for 002-Samples')
    parser.add_argument('-t', '--tag', type=str, default='Dump',
                       help='Create named tag for this run (e.g., baseline, paper_v1)')
    parser.add_argument('--force', action='store_true',
                       help='Regenerate outputs even if output files already exist for this config hash')
    parser.add_argument('--printHash', action='store_true',
                       help='Print the config hash and exit (useful for debugging)')

    # --- lxplus: DAS querying / golden JSON / lumi info -----------------------------
    parser.add_argument('--getFileList', action='store_true',
                       help='[1][lxplus] Run getFileList.py to fetch file lists from DAS')
    parser.add_argument('--getDatasetInfo', action='store_true',
                       help='[1][lxplus] Run getDatasetInfo.py to fetch dataset info from DAS')
    parser.add_argument('--downloadGoldenJSONs', action='store_true',
                       help='[1] Download golden JSON files specified in config')
    parser.add_argument('--getLumiInformation', action='store_true',
                       help='[1][lxplus] Run getLumiInformation.py to fetch luminosity information using brilcalc')
    parser.add_argument('--aggregrateDatasetInfo', action='store_true',
                       help='[2] Aggregate dataset info from individual dataset info JSON files generated from '
                            '--getDatasetInfo into a single JSON file for each era: era_aggregated_dataset_info.json')
    parser.add_argument('--getFileInfo', action='store_true',
                       help='[2][lxplus] Run getFileInfo.py to fetch per-file run-lumi information from DAS')
    parser.add_argument('--generateRunLumiFiles', action='store_true',
                       help='[2] Run generateRunLumiFiles.py to generate brilcalc-friendly run-lumi JSON files '
                            'from the output of --getFileInfo')
    parser.add_argument('--generateDASDatasetJSON', action='store_true',
                       help='[2] Build DAS_{era}_dataset.json (remote LFN -> "Events" map) from the file lists '
                            'obtained via --getFileList. This is the DAS-side dataset JSON consumed by '
                            '--submitPreSelectionJobs -- not to be confused with --generatePreselectionDatasetJSON.')

    # --- lxplus: CRAB submission / monitoring ----------------------------------------
    parser.add_argument('--submitPreSelectionJobs', action='store_true',
                       help='[3][lxplus][CRAB] Submit pre-selection jobs to CRAB based on the DAS dataset JSON '
                            'generated by --generateDASDatasetJSON. Uses scripts/crab/submit_preselection_flexible.py.')
    parser.add_argument('--checkCrabStatus', action='store_true',
                       help='[4][lxplus][CRAB] Check CRAB job status for jobs submitted with --submitPreSelectionJobs. '
                            'Uses scripts/crab/checkStatus.py.')
    parser.add_argument('--resubmitFailedCrabJobs', action='store_true',
                       help='[4][lxplus][CRAB] With --checkCrabStatus: resubmit failed CRAB jobs.')
    parser.add_argument('--removeSubmitFailedCrabJobs', action='store_true',
                       help='[4][lxplus][CRAB] With --checkCrabStatus: remove CRAB jobs that never submitted successfully.')

    # --- local disk: preselection dataset JSON for 003-ObjectSelectionI --------------
    parser.add_argument('--generatePreselectionDatasetJSON', action='store_true',
                       help='[5] Scan {STORAGE}/preselection/{tag}/{era} on local disk for CRAB output ROOT files '
                            '(after copying them down from EOS) and generate preselection_{era}_datasets.json, '
                            'the input format expected by 003-ObjectSelectionI.')

    parser.add_argument('--getStatus', action='store_true',
                       help='[6] Get overall status of the preselection processing by comparing expected number of '
                            'files from DAS with the number of files obtained from getFileInfo.py, the number of '
                            'files for which dataset JSON file is generated, the number of CRAB jobs submitted for '
                            'pre-selection, and the number of pre-selection output root files found on EOS.')

    parser.add_argument('--filter', nargs='+', default=None, metavar='FILTER',
                       help='Filter by era[/DataMC[/group[/dataset]]]. Use * as wildcard at any level. '
                            'Multiple filters are OR-ed. E.g.: --filter UL2017 --filter UL2018/MC_mu/SingleTop')

    args = parser.parse_args()

    # parsing arguments
    print("Arguments:")
    print(f"  --tag: {args.tag}")
    print(f"  --force: {args.force}")
    print(f"  --getFileList: {args.getFileList}")
    print(f"  --getDatasetInfo: {args.getDatasetInfo}")
    print(f"  --downloadGoldenJSONs: {args.downloadGoldenJSONs}")
    print(f"  --getLumiInformation: {args.getLumiInformation}")
    print(f"  --aggregrateDatasetInfo: {args.aggregrateDatasetInfo}")
    print(f"  --getFileInfo: {args.getFileInfo}")
    print(f"  --generateRunLumiFiles: {args.generateRunLumiFiles}")
    print(f"  --generateDASDatasetJSON: {args.generateDASDatasetJSON}")
    print(f"  --submitPreSelectionJobs: {args.submitPreSelectionJobs}")
    print(f"  --checkCrabStatus: {args.checkCrabStatus}")
    print(f"  --resubmitFailedCrabJobs: {args.resubmitFailedCrabJobs}")
    print(f"  --removeSubmitFailedCrabJobs: {args.removeSubmitFailedCrabJobs}")
    print(f"  --generatePreselectionDatasetJSON: {args.generatePreselectionDatasetJSON}")
    print(f"  --getStatus: {args.getStatus}")
    print(f"  --filter: {args.filter}")
    print(f"  --printHash: {args.printHash}")

    # Paths
    base_dir = Path(__file__).parent.parent
    config_path = base_dir / 'config.yaml'
    outputs_base = base_dir / 'outputs' / f'{args.tag}'
    history_file = base_dir / 'run_history.txt'

    print(f"Using config: {config_path}")

    # Load config and compute hash
    config = utils.load_config(config_path)

    # Create output directory
    output_dir, config_hash, is_new_run = utils.create_output_directory(
        outputs_base, config_path
    )
    if is_new_run:
        print(f"Config file has changed. Created new output directory: {output_dir}")
    else:
        print(f"No changes in config. Output directory already exists: {output_dir}")

    # Create or update the 'latest' symlink to point to the current output directory
    latest_link = outputs_base / 'latest'
    if latest_link.exists() or latest_link.is_symlink():
        latest_link.unlink()
    latest_link.symlink_to(output_dir.name)
    print(f"Updated symlink: {latest_link} -> {output_dir.name}")

    if args.printHash:
        print(f"Config hash: {config_hash}")
        return 0

    # Run getFileList.py if requested
    if args.getFileList:
        print("\nRunning getFileList.py to fetch file lists from DAS...")
        get_file_list_script = base_dir / 'scripts' / 'getFileList.py'
        if not get_file_list_script.exists():
            print(f"Error: {get_file_list_script} not found!")
            return 1

        for era in config['DASQueries']:
            print(f"\nFetching file list for era: {era}")
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name, das_query in config['DASQueries'][era][DataMC][group].items():
                        print(f"    Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        output_filename = f"{era}_{DataMC}_{group}_{dataset_name}_file_list.json"
                        queryResults_dir = output_dir / era / DataMC / group / dataset_name
                        queryResults_dir.mkdir(parents=True, exist_ok=True)
                        output_file_path = queryResults_dir / output_filename
                        if output_file_path.exists() and not args.force:
                            print(f"    Output file already exists: {output_file_path} and --force not specified. Skipping DAS query.")
                            continue
                        query = "file dataset={dataset}".format(dataset=das_query)
                        cmd = f"python3 {get_file_list_script} -q \"{query}\" -o {output_filename} -outDir {queryResults_dir}"
                        print(f"    Executing command: {cmd}")
                        result = subprocess.run(cmd, shell=True)
                        if result.returncode != 0:
                            print(f"Error running getFileList.py for dataset: {dataset_name}")
                            return 1
                        else:
                            print(f"    Successfully fetched file list and saved to: {queryResults_dir / output_filename}")

    # Run getDatasetInfo.py if requested
    if args.getDatasetInfo:
        print("\nRunning getDatasetInfo.py to fetch dataset info from DAS...")
        get_dataset_info_script = base_dir / 'scripts' / 'getDatasetInfo.py'
        if not get_dataset_info_script.exists():
            print(f"Error: {get_dataset_info_script} not found!")
            return 1

        for era in config['DASQueries']:
            print(f"\nFetching dataset info for era: {era}")
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name, das_query in config['DASQueries'][era][DataMC][group].items():
                        print(f"    Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        output_filename = f"{era}_{DataMC}_{group}_{dataset_name}_dataset_info.json"
                        queryResults_dir = output_dir / era / DataMC / group / dataset_name
                        queryResults_dir.mkdir(parents=True, exist_ok=True)
                        output_file_path = queryResults_dir / output_filename
                        if output_file_path.exists() and not args.force:
                            print(f"    Output file already exists: {output_file_path} and --force not specified. Skipping DAS query.")
                            continue
                        query = "dataset={dataset} | grep dataset.nevents | grep dataset.num_file".format(dataset=das_query)
                        cmd = f"python3 {get_dataset_info_script} -q \"{query}\" -o {output_filename} -outDir {queryResults_dir}"
                        print(f"    Executing command: {cmd}")
                        result = subprocess.run(cmd, shell=True)
                        if result.returncode != 0:
                            print(f"Error running getDatasetInfo.py for dataset: {dataset_name}")
                            return 1
                        else:
                            print(f"    Successfully fetched dataset info and saved to: {queryResults_dir / output_filename}")

    # Download golden JSONs if requested
    if args.downloadGoldenJSONs:
        print("\nDownloading golden JSON files specified in config...")
        download_golden_json_script = base_dir / 'scripts' / 'downloadGoldenJsons.py'
        if not download_golden_json_script.exists():
            print(f"Error: {download_golden_json_script} not found!")
            return 1
        for era, url in config['golden_json_urls'].items():
            if not matches_filter(args.filter, era):
                continue
            output_filename = f"{era}_goldenJSON.json"
            output_directory = output_dir / era
            output_directory.mkdir(parents=True, exist_ok=True)
            output_file_path = output_directory / output_filename
            if output_file_path.exists() and not args.force:
                print(f"  Golden JSON for era {era} already exists at: {output_file_path} and --force not specified. Skipping download.")
                continue
            cmd = f"python3 {download_golden_json_script} -u {url} -o {output_filename} -outDir {output_directory}"
            print(f"Executing command: {cmd}")
            result = subprocess.run(cmd, shell=True)
            if result.returncode != 0:
                print(f"Error downloading golden JSON for era: {era}")
                return 1
            else:
                print(f"Successfully downloaded golden JSON for era: {era} and saved to: {output_directory / output_filename}")

    # Aggregrate dataset info from individual dataset info JSON files generated from --getDatasetInfo
    if args.aggregrateDatasetInfo:
        print("\nAggregating dataset info from individual dataset info JSON files generated from --getDatasetInfo into a single JSON file for each era...")
        for era in config['DASQueries']:
            if not matches_filter(args.filter, era):
                continue
            aggregated_info = {}
            eraEvents = 0
            eraFiles = 0
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                aggregated_info[DataMC] = {}
                DataMCTotalEvents = 0
                DataMCTotalFiles = 0
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    aggregated_info[DataMC][group] = {}
                    groupEvents = 0
                    groupFiles = 0
                    for dataset_name in config['DASQueries'][era][DataMC][group]:
                        print(f"      Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        dataset_info_json = output_dir / era / DataMC / group / dataset_name / f"{era}_{DataMC}_{group}_{dataset_name}_dataset_info.json"
                        if not dataset_info_json.exists():
                            print(f"Error: Dataset info JSON file not found for dataset {dataset_name} at expected location: {dataset_info_json}. Please ensure the dataset info is fetched before running this aggregation step.")
                            continue
                        with open(dataset_info_json) as f:
                            dataset_info = json.load(f)
                        aggregated_info[DataMC][group][dataset_name] = dataset_info
                        num_events = dataset_info.get('num_events', 0)
                        num_files = dataset_info.get('num_files', 0)
                        groupEvents += num_events
                        groupFiles += num_files
                    aggregated_info[DataMC][group]['group_total'] = {
                        'num_events': groupEvents,
                        'num_files': groupFiles
                    }
                    DataMCTotalEvents += groupEvents
                    DataMCTotalFiles += groupFiles
                aggregated_info[DataMC]['DataMC_total'] = {
                    'num_events': DataMCTotalEvents,
                    'num_files': DataMCTotalFiles
                }
                eraEvents += DataMCTotalEvents
                eraFiles += DataMCTotalFiles
            aggregated_info['era_total'] = {
                'num_events': eraEvents,
                'num_files': eraFiles
            }
            output_directory = output_dir / era
            output_directory.mkdir(parents=True, exist_ok=True)
            output_filename = f"{era}_aggregated_dataset_info.json"
            output_file_path = output_directory / output_filename
            if output_file_path.exists() and not args.force:
                print(f"  Aggregated dataset info JSON for era {era} already exists at: {output_file_path} and --force not specified. Skipping aggregation.")
                continue
            with open(output_file_path, 'w') as f:
                json.dump(aggregated_info, f, indent=4)
            print(f"  Successfully aggregated dataset info for era: {era} and saved to: {output_file_path}")

    # Get luminosity information using brilcalc if requested
    if args.getLumiInformation:
        print("\nRunning getLumiInformation.py to fetch luminosity information using brilcalc...")
        get_lumi_info_script = base_dir / 'scripts' / 'getLumiInformation.py'
        if not get_lumi_info_script.exists():
            print(f"Error: {get_lumi_info_script} not found!")
            return 1
        for era in config['DASQueries']:
            if not matches_filter(args.filter, era):
                continue
            print(f"\nFetching luminosity information for era: {era}")
            golden_json_path = output_dir / era / f"{era}_goldenJSON.json"
            if not golden_json_path.exists():
                print(f"Error: Golden JSON file not found for era {era} at expected location: {golden_json_path}. Please ensure the golden JSON is downloaded before fetching luminosity information.")
                continue
            output_filename = f"{era}_lumi_info.csv"
            lumi_info_dir = output_dir / era
            lumi_info_dir.mkdir(parents=True, exist_ok=True)
            output_file_path = lumi_info_dir / output_filename
            if output_file_path.exists() and not args.force:
                print(f"  Luminosity information for era {era} already exists at: {output_file_path} and --force not specified. Skipping luminosity information retrieval.")
                continue
            cmd = f"python3 {get_lumi_info_script} --json {golden_json_path} -o {output_filename} --outDir {lumi_info_dir}"
            print(f"Executing command: {cmd}")
            result = subprocess.run(cmd, shell=True)
            if result.returncode != 0:
                print(f"Error fetching luminosity information for era: {era}")
                return 1
            else:
                print(f"Successfully fetched luminosity information for era: {era} and saved to: {lumi_info_dir / output_filename}")

    # Get file run-lumi information from DAS if requested
    if args.getFileInfo:
        print("\nRunning getFileInfo.py to fetch file run-lumi information from DAS...")
        get_file_info_script = base_dir / 'scripts' / 'getFileInfo.py'
        if not get_file_info_script.exists():
            print(f"Error: {get_file_info_script} not found!")
            return 1
        for era in config['DASQueries']:
            print(f"\nFetching file run-lumi information for era: {era}")
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name, das_query in config['DASQueries'][era][DataMC][group].items():
                        print(f"      Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        dataset_files_json = output_dir / era / DataMC / group / dataset_name / f"{era}_{DataMC}_{group}_{dataset_name}_file_list.json"
                        if not dataset_files_json.exists():
                            print(f"Error: File list JSON not found for dataset {dataset_name} at expected location: {dataset_files_json}. Please ensure the file list is fetched before fetching file run-lumi information.")
                            continue
                        fileList = json.load(open(dataset_files_json))
                        print(f"    Found {len(fileList)} files in file list JSON: {dataset_files_json}")
                        for file in fileList:
                            file_name = file["file"][0]["name"]
                            file_id = file["file"][0]["file_id"]
                            output_directory = output_dir / era / DataMC / group / dataset_name / f"file_{file_id}"
                            output_filename = f"{era}_{DataMC}_{group}_{dataset_name}_file{file_id}_run_lumi_info.json"
                            output_directory.mkdir(parents=True, exist_ok=True)
                            output_file_path = output_directory / output_filename
                            if output_file_path.exists() and not args.force:
                                print(f"      Run-lumi information for file {file_name} already exists at: {output_file_path} and --force not specified. Skipping run-lumi information retrieval for this file.")
                                continue
                            query = f"lumi file={file_name}"
                            cmd = f"python3 {get_file_info_script} -q \"{query}\" -o {output_filename} -outDir {output_directory}"
                            print(f"      Executing command: {cmd}")
                            result = subprocess.run(cmd, shell=True)
                            if result.returncode != 0:
                                print(f"Error fetching run-lumi information for file: {file_name}")
                                continue
                            else:
                                print(f"      Successfully fetched run-lumi information for file: {file_name} and saved to: {output_directory / output_filename}")

    # Generate brilcalc friendly run-lumi JSON files for each data file if requested
    if args.generateRunLumiFiles:
        print("\nRunning generateRunLumiFiles.py to generate brilcalc friendly run-lumi JSON files from the output of getFileInfo.py...")
        generate_run_lumi_files_script = base_dir / 'scripts' / 'generateRunLumiFiles.py'
        if not generate_run_lumi_files_script.exists():
            print(f"Error: {generate_run_lumi_files_script} not found!")
            return 1
        for era in config['DASQueries']:
            print(f"\nGenerating run-lumi JSON files for era: {era}")
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name, das_query in config['DASQueries'][era][DataMC][group].items():
                        print(f"      Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        dataset_files_json = output_dir / era / DataMC / group / dataset_name / f"{era}_{DataMC}_{group}_{dataset_name}_file_list.json"
                        if not dataset_files_json.exists():
                            print(f"Error: File list JSON not found for dataset {dataset_name} at expected location: {dataset_files_json}. Please ensure the file list is fetched before generating run-lumi JSON files.")
                            continue
                        fileList = json.load(open(dataset_files_json))
                        print(f"    Found {len(fileList)} files in file list JSON: {dataset_files_json}")
                        for file in fileList:
                            file_id = file["file"][0]["file_id"]
                            file_info_json = output_dir / era / DataMC / group / dataset_name / f"file_{file_id}" / f"{era}_{DataMC}_{group}_{dataset_name}_file{file_id}_run_lumi_info.json"
                        if not file_info_json.exists():
                            print(f"Error: File run-lumi information JSON not found for file ID {file_id} at expected location: {file_info_json}. Please ensure the file run-lumi information is fetched before generating run-lumi JSON files for this file.")
                            continue
                        output_directory = output_dir / era / DataMC / group / dataset_name / f"file_{file_id}"
                        output_filename = f"{era}_{DataMC}_{group}_{dataset_name}_file{file_id}_run_lumi.json"
                        output_file_path = output_directory / output_filename
                        if output_file_path.exists() and not args.force:
                            print(f"      Run-lumi JSON file for file ID {file_id} already exists at: {output_file_path} and --force not specified. Skipping generation of run-lumi JSON file for this file.")
                            continue
                        cmd = f"python3 {generate_run_lumi_files_script} -i {file_info_json} -o {output_filename} --outDir {output_directory}"
                        print(f"      Executing command: {cmd}")
                        result = subprocess.run(cmd, shell=True)
                        if result.returncode != 0:
                            print(f"Error generating run-lumi JSON file for file ID: {file_id}")
                            continue
                        else:
                            print(f"      Successfully generated run-lumi JSON file for file ID: {file_id} and saved to: {output_directory / output_filename}")

    # Build DAS_{era}_dataset.json (remote LFN dataset map, feeds CRAB submission)
    if args.generateDASDatasetJSON:
        print("\nGenerating DAS dataset JSON files from the file lists obtained from --getFileList...")
        for era in config['DASQueries']:
            if not matches_filter(args.filter, era):
                continue
            print(f"\nGenerating DAS dataset JSON for era: {era}")
            datasetJSON = {}
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                datasetJSON[DataMC] = {}
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    datasetJSON[DataMC][group] = {}
                    for dataset_name, das_query in config['DASQueries'][era][DataMC][group].items():
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        datasetJSON[DataMC][group][dataset_name] = {}
                        print(f"      Dataset: {dataset_name}")
                        dataset_files_json = output_dir / era / DataMC / group / dataset_name / f"{era}_{DataMC}_{group}_{dataset_name}_file_list.json"
                        if not dataset_files_json.exists():
                            print(f"Error: File list JSON not found for dataset {dataset_name} at expected location: {dataset_files_json}. Please ensure the file list is fetched before generating dataset JSON file.")
                            continue
                        fileList = json.load(open(dataset_files_json))
                        for entry in fileList:
                            file_name = entry["file"][0]["name"]
                            datasetJSON[DataMC][group][dataset_name][file_name] = "Events"
            output_directory = output_dir / era
            output_directory.mkdir(parents=True, exist_ok=True)
            output_filename = f"DAS_{era}_dataset.json"
            output_file_path = output_directory / output_filename
            if output_file_path.exists() and not args.force:
                print(f"      DAS dataset JSON file for era {era} already exists at: {output_file_path} and --force not specified. Skipping generation.")
                continue
            with open(output_file_path, 'w') as f:
                json.dump(datasetJSON, f, indent=4)
            print(f"      Successfully generated DAS dataset JSON file for era {era} and saved to: {output_file_path}")

    # Submit pre-selection jobs to CRAB
    if args.submitPreSelectionJobs:
        print("\nSubmitting pre-selection jobs to CRAB based on the DAS dataset JSON generated from --generateDASDatasetJSON...")
        submit_preselection_script = base_dir / 'scripts' / 'crab' / 'submit_preselection_flexible.py'
        if not submit_preselection_script.exists():
            print(f"Error: {submit_preselection_script} not found!")
            return 1
        for era in config['DASQueries']:
            print(f"\nSubmitting pre-selection jobs for era: {era}")
            dataset_json_path = output_dir / era / f"DAS_{era}_dataset.json"
            if not dataset_json_path.exists():
                print(f"Error: DAS dataset JSON file not found for era {era} at expected location: {dataset_json_path}. Please ensure --generateDASDatasetJSON has been run before submitting pre-selection jobs.")
                continue
            golden_json_path = output_dir / era / f"{era}_goldenJSON.json"
            if not golden_json_path.exists():
                print(f"Error: Golden JSON file not found for era {era} at expected location: {golden_json_path}. Please ensure the golden JSON is downloaded before submitting pre-selection jobs.")
                continue
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name in config['DASQueries'][era][DataMC][group]:
                        print(f"      Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        lfn_base = config['LFN_Base'].rstrip('/')
                        lfn_path = f"{lfn_base}/preselection/{args.tag}/{config_hash}/{era}/{DataMC}/{group}/{dataset_name}"
                        work_area = output_dir / era / DataMC / group / dataset_name / "crab_preselection"
                        command = f"python3 {submit_preselection_script} --submit --era {era} --das-json {dataset_json_path} --golden-json {golden_json_path} --output-lfn {lfn_path} --work-area {work_area} --include '{DataMC}/{group}/{dataset_name}'"
                        print(f"      Executing command: {command}")
                        result = subprocess.run(command, shell=True)
                        if result.returncode != 0:
                            print(f"Error submitting pre-selection jobs for dataset: {dataset_name}")
                            continue
                        else:
                            print(f"      Successfully submitted pre-selection jobs for dataset: {dataset_name} with CRAB and saved logs to: {work_area}")

    # Check CRAB job status
    if args.checkCrabStatus:
        print("\nChecking CRAB job status for pre-selection jobs submitted with --submitPreSelectionJobs...")
        check_crab_status_script = base_dir / 'scripts' / 'crab' / 'checkStatus.py'
        if not check_crab_status_script.exists():
            print(f"Error: {check_crab_status_script} not found!")
            return 1
        for era in config['DASQueries']:
            print(f"\nChecking CRAB status for era: {era}")
            for DataMC in config['DASQueries'][era]:
                print(f"  DataMC: {DataMC}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"    Group: {group}")
                    for dataset_name in config['DASQueries'][era][DataMC][group]:
                        print(f"      Dataset: {dataset_name}")
                        if not matches_filter(args.filter, era, DataMC, group, dataset_name):
                            continue
                        work_area = output_dir / era / DataMC / group / dataset_name / "crab_preselection"
                        command = f"python3 {check_crab_status_script} -d {work_area}"
                        if args.resubmitFailedCrabJobs:
                            command += " --resubmit"
                        if args.removeSubmitFailedCrabJobs:
                            command += " --removeSubmitFailed"
                        print(f"      Executing command: {command}")
                        result = subprocess.run(command, shell=True)
                        if result.returncode != 0:
                            print(f"Error checking CRAB status for dataset: {dataset_name}")
                            continue
                        else:
                            print(f"      Successfully checked CRAB status for dataset: {dataset_name}. Check the output above for details.")

    # Scan local disk for CRAB output ROOT files (once copied down from EOS) and
    # build preselection_{era}_datasets.json, the input 003-ObjectSelectionI expects.
    if args.generatePreselectionDatasetJSON:
        print("\nGenerating preselection dataset JSON files from local disk (scripts/generateDatasetJSON.py)...")
        storageBase = utils.resolve_storage_path(config)
        print(f"Using storage base: {storageBase}")
        for era in config['DASQueries']:
            if not matches_filter(args.filter, era):
                print(f"Skipping era {era} due to filter")
                continue
            generateJSON_script = base_dir / 'scripts' / 'generateDatasetJSON.py'
            if not generateJSON_script.exists():
                print(f"Error: {generateJSON_script} does not exist. Please make sure it is in the correct location.")
                return 1
            output_json_name = f"preselection_{era}_datasets.json"
            output_json_path = output_dir / era / output_json_name
            if output_json_path.exists() and not args.force:
                print(f"Output JSON file already exists for {era} and --force not set. Skipping: {output_json_path}")
                continue
            base_directory = str(Path(storageBase) / "preselection" / args.tag / config_hash / era)
            cmd = [
                'python', str(generateJSON_script),
                '--outputDirectory', str(output_dir / era),
                '--outputFileName', output_json_name,
                '--baseDirectory', base_directory
            ]
            print(f"Running command: {' '.join(cmd)}")
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                print(f"Error running generateDatasetJSON.py for {era}:\n{result.stderr}")
                return 1
            else:
                print(f"Successfully generated preselection dataset JSON for {era}: {output_json_path}")

    # Overall status across DAS expectations / getFileInfo / dataset JSON / CRAB / EOS output
    if args.getStatus:
        print("\nGetting overall status of the preselection processing...")
        eos_base = f"{utils.eos_path_from_lfn_base(config['LFN_Base'])}/preselection/{args.tag}/{config_hash}"
        for era in config['DASQueries']:
            if not matches_filter(args.filter, era):
                continue
            print(f"\nStatus for era: {era}")
            aggregated_info_json = output_dir / era / f"{era}_aggregated_dataset_info.json"
            if not aggregated_info_json.exists():
                print(f"Error: Aggregated dataset info JSON file not found for era {era} at expected location: {aggregated_info_json}. Please ensure the aggregated dataset info JSON is generated before checking status.")
                continue
            with open(aggregated_info_json) as f:
                aggregated_info = json.load(f)
            DAS_expected_files = aggregated_info['era_total']['num_files']
            print(f"  Total files according to DAS: {DAS_expected_files}")

            getFileInfo_files = list(output_dir.glob(f"{era}/**/*_file*_run_lumi_info.json"))
            num_getFileInfo_files = len(getFileInfo_files)
            print(f"  Number of files with run-lumi information obtained from getFileInfo.py: {num_getFileInfo_files}")

            dataset_json_file = output_dir / era / f"DAS_{era}_dataset.json"
            num_dataset_json_files = 0
            with open(dataset_json_file) as f:
                dataset_json = json.load(f)
            for DataMC in dataset_json:
                for group in dataset_json[DataMC]:
                    for dataset_name in dataset_json[DataMC][group]:
                        num_dataset_json_files += len(dataset_json[DataMC][group][dataset_name])
            print(f"  Number of files for which dataset JSON file is generated: {num_dataset_json_files}")

            crab_preselection_dirs = list(output_dir.glob(f"{era}/**/crab_preselection"))
            num_crab_preselection_jobs = len(crab_preselection_dirs)
            print(f"  Number of CRAB pre-selection jobs submitted: {num_crab_preselection_jobs}")

            crab_job_expected_output_dir = f"{eos_base}/{era}/"
            num_preselection_output_files = len(list(Path(crab_job_expected_output_dir).glob(f"**/*.root")))
            print(f"  Number of pre-selection output root files found at expected location {crab_job_expected_output_dir}: {num_preselection_output_files}")
            for DataMC in config['DASQueries'][era]:
                print(f"      Getting status for era/DataMC: {era}/{DataMC}")
                DataMC_expected_files = aggregated_info[DataMC]['DataMC_total']['num_files']
                print(f"        Total files according to DAS for {era}/{DataMC}: {DataMC_expected_files}")
                getFileInfo_files = list(output_dir.glob(f"{era}/{DataMC}/**/*_file*_run_lumi_info.json"))
                num_getFileInfo_files = len(getFileInfo_files)
                print(f"        Number of files with run-lumi information obtained from getFileInfo.py for {era}/{DataMC}: {num_getFileInfo_files}")
                dataset_json_file = output_dir / era / f"DAS_{era}_dataset.json"
                num_dataset_json_files = 0
                with open(dataset_json_file) as f:
                    dataset_json = json.load(f)
                for group in dataset_json[DataMC]:
                    for dataset_name in dataset_json[DataMC][group]:
                        num_dataset_json_files += len(dataset_json[DataMC][group][dataset_name])
                print(f"        Number of files for which dataset JSON file is generated for {era}/{DataMC}: {num_dataset_json_files}")
                crab_preselection_dirs = list(output_dir.glob(f"{era}/{DataMC}/**/crab_preselection"))
                num_crab_preselection_jobs = len(crab_preselection_dirs)
                print(f"        Number of CRAB pre-selection jobs submitted for {era}/{DataMC}: {num_crab_preselection_jobs}")
                crab_job_expected_output_dir = f"{eos_base}/{era}/{DataMC}/"
                num_preselection_output_files = len(list(Path(crab_job_expected_output_dir).glob(f"**/*.root")))
                print(f"        Number of pre-selection output root files found at expected location {crab_job_expected_output_dir}: {num_preselection_output_files}")
                for group in config['DASQueries'][era][DataMC]:
                    print(f"            Getting status for era/DataMC/Group: {era}/{DataMC}/{group}")
                    group_expected_files = aggregated_info[DataMC][group]['group_total']['num_files']
                    print(f"              Total files according to DAS for {era}/{DataMC}/{group}: {group_expected_files}")
                    getFileInfo_files = list(output_dir.glob(f"{era}/{DataMC}/{group}/**/*_file*_run_lumi_info.json"))
                    num_getFileInfo_files = len(getFileInfo_files)
                    print(f"              Number of files with run-lumi information obtained from getFileInfo.py for {era}/{DataMC}/{group}: {num_getFileInfo_files}")
                    dataset_json_file = output_dir / era / f"DAS_{era}_dataset.json"
                    num_dataset_json_files = 0
                    with open(dataset_json_file) as f:
                        dataset_json = json.load(f)
                    for dataset_name in dataset_json[DataMC][group]:
                        num_dataset_json_files += len(dataset_json[DataMC][group][dataset_name])
                    print(f"              Number of files for which dataset JSON file is generated for {era}/{DataMC}/{group}: {num_dataset_json_files}")
                    crab_preselection_dirs = list(output_dir.glob(f"{era}/{DataMC}/{group}/**/crab_preselection"))
                    num_crab_preselection_jobs = len(crab_preselection_dirs)
                    print(f"              Number of CRAB pre-selection jobs submitted for {era}/{DataMC}/{group}: {num_crab_preselection_jobs}")
                    crab_job_expected_output_dir = f"{eos_base}/{era}/{DataMC}/{group}/"
                    num_preselection_output_files = len(list(Path(crab_job_expected_output_dir).glob(f"**/*.root")))
                    print(f"              Number of pre-selection output root files found at expected location {crab_job_expected_output_dir}: {num_preselection_output_files}")
                    for dataset_name in config['DASQueries'][era][DataMC][group]:
                        print(f"                  Getting status for era/DataMC/Group/Dataset: {era}/{DataMC}/{group}/{dataset_name}")
                        dataset_expected_files = aggregated_info[DataMC][group][dataset_name]['num_files']
                        print(f"                    Total files according to DAS for {era}/{DataMC}/{group}/{dataset_name}: {dataset_expected_files}")
                        getFileInfo_files = list(output_dir.glob(f"{era}/{DataMC}/{group}/{dataset_name}/**/*_file*_run_lumi_info.json"))
                        num_getFileInfo_files = len(getFileInfo_files)
                        print(f"                    Number of files with run-lumi information obtained from getFileInfo.py for {era}/{DataMC}/{group}/{dataset_name}: {num_getFileInfo_files}")
                        dataset_json_file = output_dir / era / f"DAS_{era}_dataset.json"
                        num_dataset_json_files = 0
                        with open(dataset_json_file) as f:
                            dataset_json = json.load(f)
                        num_dataset_json_files += len(dataset_json[DataMC][group][dataset_name])
                        print(f"                    Number of files for which dataset JSON file is generated for {era}/{DataMC}/{group}/{dataset_name}: {num_dataset_json_files}")
                        crab_preselection_dirs = list(output_dir.glob(f"{era}/{DataMC}/{group}/{dataset_name}/**/crab_preselection"))
                        num_crab_preselection_jobs = len(crab_preselection_dirs)
                        print(f"                    Number of CRAB pre-selection jobs submitted for {era}/{DataMC}/{group}/{dataset_name}: {num_crab_preselection_jobs}")
                        crab_job_expected_output_dir = f"{eos_base}/{era}/{DataMC}/{group}/{dataset_name}/"
                        num_preselection_output_files = len(list(Path(crab_job_expected_output_dir).glob(f"**/*.root")))
                        print(f"                    Number of pre-selection output root files found at expected location {crab_job_expected_output_dir}: {num_preselection_output_files}")
    exit(0)


if __name__ == '__main__':
    sys.exit(main())
