jsonPath: 
  UL2016preVFP: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/Datasets/dataFiles_UL2016preVFP.json"
  UL2016postVFP: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/Datasets/dataFiles_UL2016postVFP.json"
  UL2017: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/Datasets/dataFiles_UL2017.json"
  UL2018: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/Datasets/dataFiles_UL2018.json"

keep_and_drop: "/home/mukund/Projects/SkimandSlim/NanoAODTools/python/postprocessing/examples/keep_and_drop.txt"

outputDir: "/mnt/disk1/skimmed_Run2/preselection"

cuts:
  UL2016preVFP:
    muon_pt_min: 20
    muon_eta_max: 3.0
    muon_id: "Muon_tightId"
    btag_wp: 0.2598
    jet_pt_min: 20
    jet_eta_max: 3.0
    min_btag_jets: 2
    min_jets: 4
    triggers:
      - "HLT_IsoMu24"
      - "HLT_IsoTkMu24"

  UL2016postVFP:
    muon_pt_min: 20
    muon_eta_max: 3.0
    btag_wp: 0.2489
    jet_pt_min: 20
    jet_eta_max: 3.0
    min_btag_jets: 2
    min_jets: 4
    triggers:
      - "HLT_IsoMu24"
      - "HLT_IsoTkMu24"

  UL2017:
    muon_pt_min: 20
    muon_eta_max: 3.0
    btag_wp: 0.3040
    jet_pt_min: 20
    jet_eta_max: 3.0
    min_btag_jets: 2
    min_jets: 4
    triggers:
      - "HLT_IsoMu27"

  UL2018:
    muon_pt_min: 20
    muon_eta_max: 3.0
    btag_wp: 0.2783
    jet_pt_min: 20
    jet_eta_max: 3.0
    min_btag_jets: 2
    min_jets: 4
    triggers:
      - "HLT_IsoMu24"
