#!/usr/bin/env python3
"""
condor/prepare_condor.py
========================
Generate HTCondor submit files for running main_new.py on lxplus.

Each condor job processes ONE (stage, era, dataset-key) combination so
that independent samples can run in parallel across the cluster, and a
single failure does not block the entire era.

Usage
-----
    # Generate submit files for ALL stages and eras
    python3 condor/prepare_condor.py --outputTag midNov

    # Generate submit files for a single stage / era
    python3 condor/prepare_condor.py --outputTag midNov --stage selection --era UL2018

After running this script:
  1. Review the generated condor/jobs/ directory.
  2. Submit: bash condor/submit_all.sh
  3. Monitor: condor_q
  4. When all jobs complete, harvest JSONs:
       python3 main_new.py -t midNov --stage selection --era UL2018 --harvest-only

Options
-------
    --outputTag    Config tag (maps to configs/<tag>/processFlow_config.yaml). [required]
    --stage        Limit to one stage (default: all stages in processFlow).
    --era          Limit to one era (default: all eras).
    --workers      Cores requested per condor job (default: 4).
    --job-flavour  HTCondor JobFlavour (default: workday = 8h).
    --repo-root    Absolute path to the NanoAODTools repo on lxplus
                   (default: read REPO_ROOT from .env, else auto-detect).
    --env-file     Path to a custom .env to source inside each job
                   (default: <repo-root>/.env).
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# .env loader (standalone, no external deps)
# ---------------------------------------------------------------------------
def _load_env(env_file=None):
    repo_root = Path(__file__).resolve().parent.parent
    if env_file is None:
        env_file = repo_root / ".env"
    else:
        env_file = Path(env_file)
    loaded = {}
    if not env_file.exists():
        return loaded
    with open(env_file) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip("'\"")
            loaded[key] = value
            if key not in os.environ:
                os.environ[key] = value
    return loaded


# ---------------------------------------------------------------------------
# YAML loader (PyYAML required)
# ---------------------------------------------------------------------------
def load_yaml(path):
    try:
        import yaml
    except ImportError:
        logging.error("PyYAML is required: pip install pyyaml")
        sys.exit(1)
    with open(path) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------

CONDOR_DIR = Path(__file__).resolve().parent

SUBMIT_TEMPLATE = """\
# Auto-generated by condor/prepare_condor.py
# Stage: {stage}   Era: {era}

universe          = vanilla
executable        = {launcher}
arguments         = {output_tag} {stage} {era} $(KEY) {workers} {sample_mode}
initialdir        = {submit_dir}
output            = {log_dir}/{stage}_{era}_$(KEY)_$(ClusterId)_$(ProcId).out
error             = {log_dir}/{stage}_{era}_$(KEY)_$(ClusterId)_$(ProcId).err
log               = {log_dir}/{stage}_{era}_$(ClusterId).log
request_cpus      = {workers}
request_memory    = 4000
+JobFlavour       = "{job_flavour}"
MY.SendCredential = True

queue KEY from {keys_file}
"""


def get_keys_for_stage_era(config, stage, era, datasets_folder):
    """Return a list of (DataMC, key) pairs that exist in the input JSON."""
    if stage not in config["processFlow"] or era not in config["processFlow"][stage]:
        return []

    flow = config["processFlow"][stage][era]
    input_stage = flow["inputStage"]
    input_tag   = flow["inputTag"]
    json_path   = Path(datasets_folder) / f"{input_tag}_{input_stage}_{era}_dataFiles.json"

    if not json_path.exists():
        logging.warning(f"Input JSON not found: {json_path}")
        return []

    with open(json_path) as f:
        data = json.load(f)

    pairs = []
    for dm in data:
        for key in data[dm]:
            if data[dm][key]:          # skip empty dicts
                pairs.append(key)
    return pairs


def write_submit_file(stage, era, keys, output_tag, repo_root, workers,
                      job_flavour, log_dir, submit_dir, sample_mode=False):
    """Write one HTCondor submit file for all keys in a (stage, era)."""
    jobs_dir = submit_dir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    keys_to_submit = keys[:1] if sample_mode else keys
    keys_file = jobs_dir / f"keys_{stage}_{era}.txt"
    with open(keys_file, "w") as f:
        for k in keys_to_submit:
            f.write(k + "\n")

    sub_file = jobs_dir / f"submit_{stage}_{era}.sub"
    content = SUBMIT_TEMPLATE.format(
        stage       = stage,
        era         = era,
        launcher    = str(submit_dir / "launcher.sh"),
        output_tag  = output_tag,
        workers     = workers,
        job_flavour = job_flavour,
        submit_dir  = str(submit_dir),
        log_dir     = str(log_dir),
        keys_file   = str(keys_file),
        sample_mode = "1" if sample_mode else "0",
    )
    with open(sub_file, "w") as f:
        f.write(content)

    return sub_file, len(keys_to_submit)


def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    _load_env()
    env = _load_env()   # also returns the dict

    repo_root_default = env.get("REPO_ROOT", str(Path(__file__).resolve().parent.parent))

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--outputTag", "-t", required=True,
                        help="Config tag (e.g. midNov)")
    parser.add_argument("--stage", "-s", default=None,
                        help="Limit to one stage")
    parser.add_argument("--era", "-e", default=None,
                        help="Limit to one era")
    parser.add_argument("--workers", "-w", type=int, default=4,
                        help="CPUs per condor job (default: 4)")
    parser.add_argument("--job-flavour", default="workday",
                        choices=["espresso", "microcentury", "longlunch",
                                 "workday", "tomorrow", "testmatch", "nextweek"],
                        help="HTCondor JobFlavour controlling max runtime (default: workday=8h)")
    parser.add_argument("--repo-root", default=repo_root_default,
                        help="Absolute path to NanoAODTools repo on lxplus "
                             "(default: REPO_ROOT from .env or auto-detected)")
    log_dir_default = env.get("LOG_DIR", str(CONDOR_DIR / "logs"))
    parser.add_argument("--log-dir", default=log_dir_default,
                        help="Directory for condor log/out/err files. "
                             "MUST be on AFS (not EOS) — HTCondor uses flock() on the .log file. "
                             "(default: LOG_DIR from .env, else condor/logs/ inside repo)")
    schedd_default = env.get("CONDOR_SCHEDD", None)
    parser.add_argument("--schedd", default=schedd_default,
                        help="HTCondor schedd name to pass to condor_submit -name. "
                             "(default: CONDOR_SCHEDD from .env, else omitted for standard schedd)")
    submit_dir_default = env.get("SUBMIT_DIR", str(CONDOR_DIR))
    parser.add_argument("--submit-dir", default=submit_dir_default,
                        help="Directory where .sub files, keys/, and job_wrapper.sh live. "
                             "MUST be on AFS when using the standard schedd — EOS paths are "
                             "rejected in submit files. "
                             "(default: SUBMIT_DIR from .env, else condor/ inside repo)")
    parser.add_argument("--test", action="store_true",
                        help="Submit only 1 key with --sample (one file per dataset). "
                             "Use this to validate the full condor→LCG→job pipeline "
                             "before submitting all jobs.")
    args = parser.parse_args()

    repo_root   = Path(args.repo_root)
    config_path = repo_root / "configs" / args.outputTag / "processFlow_config.yaml"
    if not config_path.exists():
        logging.error(f"processFlow config not found: {config_path}")
        sys.exit(1)

    config = load_yaml(config_path)
    datasets_folder = repo_root / config["DatasetJSONFolder"]
    log_dir = Path(args.log_dir)
    log_dir.mkdir(parents=True, exist_ok=True)
    submit_dir = Path(args.submit_dir)
    submit_dir.mkdir(parents=True, exist_ok=True)

    # Copy job_wrapper.sh to submit_dir if it isn't already there
    import shutil
    wrapper_src = CONDOR_DIR / "job_wrapper.sh"
    wrapper_dst = submit_dir / "job_wrapper.sh"
    if wrapper_src.resolve() != wrapper_dst.resolve():
        shutil.copy2(wrapper_src, wrapper_dst)
        wrapper_dst.chmod(0o755)
        logging.info(f"Copied job_wrapper.sh → {wrapper_dst}")

    # Write REPO_ROOT base64-encoded to a conf file on AFS.
    # The schedd scans ALL files in the submit infrastructure for /eos/ strings,
    # so we cannot store the raw EOS path anywhere on disk.
    # The launcher decodes it at job runtime with base64 -d.
    import base64
    repo_root_conf = submit_dir / "repo_root.conf"
    repo_root_conf.write_bytes(base64.b64encode(str(repo_root).encode()))
    logging.info(f"Written repo_root.conf (base64-encoded) → {repo_root_conf}")

    # Generate a thin AFS launcher with no EOS strings anywhere.
    # REPO_ROOT is recovered at runtime by decoding repo_root.conf.
    launcher = submit_dir / "launcher.sh"
    with open(launcher, "w") as f:
        f.write("#!/bin/bash\n")
        f.write("# Auto-generated by condor/prepare_condor.py\n")
        f.write(f'REPO_ROOT=$(base64 -d "{repo_root_conf}")\n')
        f.write(f'exec "{submit_dir}/job_wrapper.sh" "$REPO_ROOT" "$@"\n')
    launcher.chmod(0o755)
    logging.info(f"Generated launcher.sh → {launcher}")

    sub_files = []
    for stage in config["processFlow"]:
        if args.stage and stage != args.stage:
            continue
        for era in config["processFlow"][stage]:
            if args.era and era != args.era:
                continue
            keys = get_keys_for_stage_era(config, stage, era, datasets_folder)
            if not keys:
                logging.warning(f"No keys found for {stage}/{era} — skipping.")
                continue
            sub_file, n_jobs = write_submit_file(
                stage       = stage,
                era         = era,
                keys        = keys,
                output_tag  = args.outputTag,
                repo_root   = str(repo_root),
                workers     = args.workers,
                job_flavour = args.job_flavour,
                log_dir     = log_dir,
                submit_dir  = submit_dir,
                sample_mode = args.test,
            )
            logging.info(f"  {sub_file.name}  ({n_jobs} keys)")
            sub_files.append(sub_file)

    if not sub_files:
        logging.warning("No submit files generated — check your --stage / --era arguments.")
        sys.exit(1)

    # Write a master submit_all.sh
    schedd_flag = f"-name {args.schedd} " if args.schedd else ""
    submit_all = submit_dir / "submit_all.sh"
    with open(submit_all, "w") as f:
        f.write("#!/bin/bash\n")
        f.write("# Auto-generated by condor/prepare_condor.py\n")
        f.write("# Submit all generated HTCondor jobs.\n\n")
        f.write("set -e\n")
        for sf in sub_files:
            f.write(f"echo 'Submitting {sf.name}'\n")
            f.write(f"condor_submit {schedd_flag}{sf}\n")
    submit_all.chmod(0o755)

    logging.info(f"\nGenerated {len(sub_files)} submit file(s).")
    logging.info(f"  Submit all: bash {submit_all}")
    logging.info(f"  Monitor:    condor_q")
    logging.info(f"  Harvest:    python3 main_new.py -t {args.outputTag} --harvest-only")


if __name__ == "__main__":
    main()
