#!/bin/bash
# Auto-generated by condor/prepare_condor.py
# Submit all generated HTCondor jobs.

set -e
echo 'Submitting submit_selection_UL2018.sub'
condor_submit /home/mukund/Projects/PhysicsTools/NanoAODTools/condor/jobs/submit_selection_UL2018.sub
