#!/bin/bash

python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/Data_mu/SingleMuon 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/Data_mu/SingleMuon/earlyApril_UL2016postVFP_Data_mu_SingleMuon.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_alt/FullyLeptonic/earlyApril_UL2016postVFP_MC_alt_FullyLeptonic.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_alt/SemiLeptonic/earlyApril_UL2016postVFP_MC_alt_SemiLeptonic.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/Tbarchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_alt/Tbarchannel/earlyApril_UL2016postVFP_MC_alt_Tbarchannel.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/Tchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_alt/Tchannel/earlyApril_UL2016postVFP_MC_alt_Tchannel.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/Diboson 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/Diboson/earlyApril_UL2016postVFP_MC_mu_Diboson.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/DrellYan 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/DrellYan/earlyApril_UL2016postVFP_MC_mu_DrellYan.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/FullyLeptonic/earlyApril_UL2016postVFP_MC_mu_FullyLeptonic.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/QCD 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/QCD/earlyApril_UL2016postVFP_MC_mu_QCD.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/SemiLeptonic/earlyApril_UL2016postVFP_MC_mu_SemiLeptonic.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/SingleTop 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/SingleTop/earlyApril_UL2016postVFP_MC_mu_SingleTop.log
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/scripts/runSelectionII.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/WJets 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionII/outputs/earlyApril/0ca8d18611ca/UL2016postVFP/MC_mu/WJets/earlyApril_UL2016postVFP_MC_mu_WJets.log
