#!/bin/bash

mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/Data_mu/SingleMuon
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/Data_mu/SingleMuon 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/Data_mu/SingleMuon/earlyApril_UL2016postVFP_Data_mu_SingleMuon.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/FullyLeptonic/earlyApril_UL2016postVFP_MC_alt_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/SemiLeptonic/earlyApril_UL2016postVFP_MC_alt_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/Tbarchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/Tbarchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/Tbarchannel/earlyApril_UL2016postVFP_MC_alt_Tbarchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/Tchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_alt/Tchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_alt/Tchannel/earlyApril_UL2016postVFP_MC_alt_Tchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/Diboson
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/Diboson 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/Diboson/earlyApril_UL2016postVFP_MC_mu_Diboson.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/DrellYan
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/DrellYan 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/DrellYan/earlyApril_UL2016postVFP_MC_mu_DrellYan.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/FullyLeptonic/earlyApril_UL2016postVFP_MC_mu_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/QCD
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/QCD 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/QCD/earlyApril_UL2016postVFP_MC_mu_QCD.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/SemiLeptonic/earlyApril_UL2016postVFP_MC_mu_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/SingleTop
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/SingleTop 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/SingleTop/earlyApril_UL2016postVFP_MC_mu_SingleTop.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/WJets
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/earlyApril_UL2016postVFP_processListJSON.json --workers 15 --filter UL2016postVFP/MC_mu/WJets 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016postVFP/MC_mu/WJets/earlyApril_UL2016postVFP_MC_mu_WJets.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/Data_mu/SingleMuon
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/Data_mu/SingleMuon 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/Data_mu/SingleMuon/earlyApril_UL2016preVFP_Data_mu_SingleMuon.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_alt/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/FullyLeptonic/earlyApril_UL2016preVFP_MC_alt_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_alt/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/SemiLeptonic/earlyApril_UL2016preVFP_MC_alt_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/Tbarchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_alt/Tbarchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/Tbarchannel/earlyApril_UL2016preVFP_MC_alt_Tbarchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/Tchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_alt/Tchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_alt/Tchannel/earlyApril_UL2016preVFP_MC_alt_Tchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/Diboson
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/Diboson 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/Diboson/earlyApril_UL2016preVFP_MC_mu_Diboson.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/DrellYan
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/DrellYan 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/DrellYan/earlyApril_UL2016preVFP_MC_mu_DrellYan.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/FullyLeptonic/earlyApril_UL2016preVFP_MC_mu_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/QCD
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/QCD 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/QCD/earlyApril_UL2016preVFP_MC_mu_QCD.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/SemiLeptonic/earlyApril_UL2016preVFP_MC_mu_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/SingleTop
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/SingleTop 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/SingleTop/earlyApril_UL2016preVFP_MC_mu_SingleTop.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/WJets
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/earlyApril_UL2016preVFP_processListJSON.json --workers 15 --filter UL2016preVFP/MC_mu/WJets 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2016preVFP/MC_mu/WJets/earlyApril_UL2016preVFP_MC_mu_WJets.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/Data_mu/SingleMuon
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/Data_mu/SingleMuon 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/Data_mu/SingleMuon/earlyApril_UL2017_Data_mu_SingleMuon.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_alt/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/FullyLeptonic/earlyApril_UL2017_MC_alt_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_alt/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/SemiLeptonic/earlyApril_UL2017_MC_alt_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/Tbarchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_alt/Tbarchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/Tbarchannel/earlyApril_UL2017_MC_alt_Tbarchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/Tchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_alt/Tchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_alt/Tchannel/earlyApril_UL2017_MC_alt_Tchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/Diboson
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/Diboson 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/Diboson/earlyApril_UL2017_MC_mu_Diboson.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/DrellYan
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/DrellYan 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/DrellYan/earlyApril_UL2017_MC_mu_DrellYan.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/FullyLeptonic/earlyApril_UL2017_MC_mu_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/QCD
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/QCD 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/QCD/earlyApril_UL2017_MC_mu_QCD.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/SemiLeptonic/earlyApril_UL2017_MC_mu_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/SingleTop
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/SingleTop 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/SingleTop/earlyApril_UL2017_MC_mu_SingleTop.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/WJets
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/earlyApril_UL2017_processListJSON.json --workers 15 --filter UL2017/MC_mu/WJets 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2017/MC_mu/WJets/earlyApril_UL2017_MC_mu_WJets.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/Data_mu/SingleMuon
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/Data_mu/SingleMuon 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/Data_mu/SingleMuon/earlyApril_UL2018_Data_mu_SingleMuon.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_alt/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/FullyLeptonic/earlyApril_UL2018_MC_alt_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_alt/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/SemiLeptonic/earlyApril_UL2018_MC_alt_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/Tbarchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_alt/Tbarchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/Tbarchannel/earlyApril_UL2018_MC_alt_Tbarchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/Tchannel
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_alt/Tchannel 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_alt/Tchannel/earlyApril_UL2018_MC_alt_Tchannel.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/Diboson
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/Diboson 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/Diboson/earlyApril_UL2018_MC_mu_Diboson.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/DrellYan
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/DrellYan 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/DrellYan/earlyApril_UL2018_MC_mu_DrellYan.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/FullyLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/FullyLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/FullyLeptonic/earlyApril_UL2018_MC_mu_FullyLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/QCD
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/QCD 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/QCD/earlyApril_UL2018_MC_mu_QCD.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/SemiLeptonic
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/SemiLeptonic 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/SemiLeptonic/earlyApril_UL2018_MC_mu_SemiLeptonic.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/SingleTop
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/SingleTop 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/SingleTop/earlyApril_UL2018_MC_mu_SingleTop.log
mkdir -p /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/WJets
python /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/scripts/runSelection.py --processListJSON /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/earlyApril_UL2018_processListJSON.json --workers 15 --filter UL2018/MC_mu/WJets 2>&1 | tee -a /home/mukund/Projects/PhysicsTools/NanoAODTools/003-ObjectSelectionI/outputs/earlyApril/e9e56867b2a8/UL2018/MC_mu/WJets/earlyApril_UL2018_MC_mu_WJets.log
